sentence = input("Enter your Sentence:")
print("Your Sentence is :"+sentence)
word1= input("Enter word to replace:")
word2= input("Enter word to replace it with:")
print("sentence.replace(word1,word2))
